#include <bgfx/defines.h>
#include <bgfx/c99/bgfx.h>

enum
{
	BGFX_RESET_NONE_ = BGFX_RESET_NONE,
	BGFX_CLEAR_COLOR_ = BGFX_CLEAR_COLOR,
	BGFX_CLEAR_DEPTH_ = BGFX_CLEAR_DEPTH,
	BGFX_FRAME_NONE_ = BGFX_FRAME_NONE,
	BGFX_BUFFER_ALLOW_RESIZE_ = BGFX_BUFFER_ALLOW_RESIZE,
	BGFX_BUFFER_INDEX32_ = BGFX_BUFFER_INDEX32,
	BGFX_TEXTURE_RT_ = BGFX_TEXTURE_RT,
	BGFX_SAMPLER_U_CLAMP_ = BGFX_SAMPLER_U_CLAMP,
	BGFX_SAMPLER_V_CLAMP_ = BGFX_SAMPLER_V_CLAMP,
	BGFX_SAMPLER_MIN_POINT_ = BGFX_SAMPLER_MIN_POINT,
	BGFX_SAMPLER_MAG_POINT_ = BGFX_SAMPLER_MAG_POINT,
	BGFX_SAMPLER_MIP_POINT_ = BGFX_SAMPLER_MIP_POINT,
	BGFX_SAMPLER_MIN_ANISOTROPIC_ = BGFX_SAMPLER_MIN_ANISOTROPIC,
};
