#include <bgfx/defines.h>
#include <bgfx/c99/bgfx.h>

enum
{
	BGFX_RESET_NONE_ = BGFX_RESET_NONE,
	BGFX_CLEAR_COLOR_ = BGFX_CLEAR_COLOR,
	BGFX_CLEAR_DEPTH_ = BGFX_CLEAR_DEPTH,
	BGFX_FRAME_NONE_ = BGFX_FRAME_NONE,
	BGFX_DISCARD_ALL_ = BGFX_DISCARD_ALL,
	BGFX_DEBUG_TEXT_ = BGFX_DEBUG_TEXT,
	BGFX_DEBUG_STATS_ = BGFX_DEBUG_STATS,
	BGFX_DEBUG_PROFILER_ = BGFX_DEBUG_PROFILER,
	BGFX_BUFFER_ALLOW_RESIZE_ = BGFX_BUFFER_ALLOW_RESIZE,
	BGFX_BUFFER_INDEX32_ = BGFX_BUFFER_INDEX32,
	BGFX_TEXTURE_RT_ = BGFX_TEXTURE_RT,
	BGFX_TEXTURE_COMPUTE_WRITE_ = BGFX_TEXTURE_COMPUTE_WRITE,
	BGFX_TEXTURE_READ_BACK_ = BGFX_TEXTURE_READ_BACK,
	BGFX_SAMPLER_U_CLAMP_ = BGFX_SAMPLER_U_CLAMP,
	BGFX_SAMPLER_V_CLAMP_ = BGFX_SAMPLER_V_CLAMP,
	BGFX_SAMPLER_MIN_POINT_ = BGFX_SAMPLER_MIN_POINT,
	BGFX_SAMPLER_MAG_POINT_ = BGFX_SAMPLER_MAG_POINT,
	BGFX_SAMPLER_MIP_POINT_ = BGFX_SAMPLER_MIP_POINT,
	BGFX_SAMPLER_MIN_ANISOTROPIC_ = BGFX_SAMPLER_MIN_ANISOTROPIC,
	BGFX_STATE_WRITE_RGB_ = BGFX_STATE_WRITE_RGB,
	BGFX_STATE_WRITE_A_ = BGFX_STATE_WRITE_A,
	BGFX_STATE_WRITE_Z_ = BGFX_STATE_WRITE_Z,
	BGFX_STATE_DEPTH_TEST_LESS_ = BGFX_STATE_DEPTH_TEST_LESS,
	BGFX_STATE_BLEND_ALPHA_ = BGFX_STATE_BLEND_ALPHA,
	BGFX_ACCESS_WRITE_ = BGFX_ACCESS_WRITE,
};
